apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-Book-deployment
  namespace: train-Book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-Book
  template:
    metadata:
      labels:
        app: train-Book
    spec:
      containers:
        - name: train-Book-container
          image: <IMAGE>
          ports:
            - containerPort: 8080
